### PR TITLE
Upgrade to Admob 21.4.0

### PR DESCRIPTION
**Pull request by Bigfoot71**
As said on the forum here is my work to upgrade to **Admob version 21.4.0**. I tried to put all the parameters back as they were originally (_sorry if I have forgotten_) because it comes from a version that I had modified a lot over time.

The most important changes are the `build.graddle` and `AdActivity.java` files (as well as in the `app/src/main` manifest due to the new way of declaring the application ID).

There is also the fact that with the update to 21.4.0 I had an overflow of the number of possible methods in the dex file that I could not solve without activating the multidex, I leave it to you to judge thereby.

I think that if possible it would be good to merge again with the love-android repository because I had to make some changes so that it could compile in the `love/src/jni` folder which comes from the latest version of the official repository.
The change that was needed was the inclusion of `<cassert>` in the `oboe` library. Replacing this folder with the most recent from the official repository solves the problem, but would it be wiser to merge completely? (not tested)

At the slightest problem or request for precision, do not hesitate, thank you for your attention.

### CODE REVIEW

**Comment by flamendless** [comment]
Have you tried building a simple android app with working admob with this? Just want to check and be fully sure. Will merge this soon. Thank you for the effort :)

**Comment by Bigfoot71** [comment]
Of course and thank you for making me think of it, I tried it with one of my games and everything worked as before, however the consents forms were not displayed for me (including in your version), I tried to look why in this update and I did not find the reason (I did not modify anything there), I then wanted to try with the code proposed by [bio1712](https://love2d.org/forums/memberlist.php?mode=viewprofile&u=136963&sid=ca63fd1371b6cd309879a21428e45e2a) in his original project (I also updated it and posted [here](https://github.com/Bigfoot71/love-android-extension-assets)) and found that I can't view banners either , I tried again then with your current version of love-android-extension and the same (can't display them for me, maybe I'm doing something wrong), the most significant thing I changed for them banners is this line `mAdView.setAdSize(AdSize.SMART_BANNER);` by this `mAdView.setAdSize(AdSize.BANNER);` because `SMART_BANNER` has become obsolete.

**Comment by flamendless** [comment]
Thank you. Will merge this asap

**Comment by flamendless** [comment]
BTW @Bigfoot71 , I suggest a built apk in the example repo of yours so others can easily download it and test it :) Also perhaps screenshots in the README?

**Comment by Bigfoot71** [comment]
Thank you it's a good idea and it's done.
https://github.com/Bigfoot71/love-android-extensions-assets

**Comment by flamendless** [comment]
Was there any need to upgrade the SDK or NDK version from the ones listed as requirements in the readme @Bigfoot71 ? You can make a follow up PR for the readme :)

**Comment by Bigfoot71** [comment]
Excuse me I'm not sure I understand about the SDK and NDK, you mean the upgrade I had to do when upgrading AdMob?

If that's the case I don't remember the exact reason because as I told you I had made a lot of modifications on my side because I have a personal version of it, I tried as much as possible to Put it back as it was originally but if I changed it there must have been a problem somewhere but I can't remember which one.

Otherwise for the readme you were talking about your repository or my example repository ([love-android-extensions-assets](https://github.com/Bigfoot71/love-android-extensions-assets)) because I don't am not sure I understand your PR request on this either? If it's for your repo, no problem, I'll do it.

**Comment by flamendless** [comment]
Hmm  I've tried syncing the love submodule and the love-android from the original repo and now the generated apk (with just a simple main.lua) fails to install :/

**Comment by Bigfoot71** [comment]
I saw your message by email but it is no longer there, as a precaution I tested your modifications **it works for me**, maybe you forgot to sign the application?

**Comment by flamendless** [comment]
That indeed was the problem haha. It's been a long time since I last generated apk for love

**Comment by Bigfoot71** [comment]
@flamendless I tried with the changes you just pushed to your repository and **the app crashes when calling any Admob-related function from Lua**, I haven't been able to find the cause yet, an idea ?

Edit: I finally got it, this line in graddle.properties: `app.activity_name=org.love2d.android.GameActivity`
Should be: `app.activity_name=org.flamendless.admob.AdActivity`

Was this change voluntary?

**Comment by flamendless** [comment]
Oh that was a mistake in merge conflict resolution when I sync the fork from the main repo. Will fix it by the end of day

**Pull request merged**
